### PR TITLE
Expanding README with auth info

### PR DESCRIPTION
**Pull request by jamescooke**
Thanks for the great Django module.

I've struggled today getting the authorisation to work with Salesforce, primarily because I'm not familiar with their API and docs. I found all the info I needed in this closed issue: https://github.com/django-salesforce/django-salesforce/issues/83

As per the suggestion there, I've added this info to the quick start in README. Hopefully it'll help other Djangonauts who don't know Salesforce well in the future.

### CODE REVIEW

**Comment by hynekcer** [comment]
Yes. It is not all. For `CONSUMER_KEY` and `CONSUMER_SECRET` can be written

> You can create them on the web by 
> ` ` ` Setup / App Setup / Create / Apps / Connected apps / New`. 
> Fill any names into `Basic information`. 
> Click `Enable OAuth Settings` in the section `API (Enable OAuth Settings)`. 
> Fill any unimportant `Callback URL`. 
> Select some OAuth Scopes from `Available OAuth Scopes`. 
> Save

The minimum is probably "Access and manage your data (api)".
I usually select only "Full access (full)", because I usually want to get the concievable maximum including the access to metadata and I have not tried anything less yet.

What is your latest experience?

**Comment by philchristensen** [comment]
Glad to accept this patch, but it would be great if you could clarify that the security code can be omitted from the password if the local IP address has been whitelisted (although certainly for new users, it may be worth circumventing the IP whitelist with the security token).

**Comment by jamescooke** [comment]
@hynekcer That looks like good additional info. By searching for some of the phrases you've used, I've found this page: https://help.salesforce.com/apex/HTViewHelpDoc?id=connected_app_create.htm , which has very detailed information. Would it be good to link to this from the README rather than duplicating Salesforce info?

My experience yesterday was that I was given access credentials for the sandbox system, but I hadn't realised that the password and token should be concatenated.

@philchristensen Thanks for the feedback. Happy to add that information about the possible omission of the security code - is there a link which the README could point people at for more info?

**Comment by hynekcer** [comment]
Yes, the link is very useful, otherwise there would be questions permanently. But it is too long, complicated and not all.

crib under the desk:
> Salesforce web / Setup / App Setup / Create / Apps / Connected apps / New. 
> Click "Enable OAuth Settings" in API, then select "Access and manage your data (api)" from available OAuth Scopes.
> Other red marked fields must be filled, but are not relevant for Django.

All test passed with this, without full access. Even Tooling API works good.

Everything for a project can work under restricted Salesforce user account if it has access to objects in your models. Introspection (inspectdb) doesn't require any permissions. Running tests for django_salesforce requires many permissions or Administrator account for sandbox.

**Comment by jamescooke** [comment]
@hynekcer Good information and crib sheet :+1: I've added this info.

@philchristensen I've added the info about whitelisting.

**Comment by hynekcer** [comment]
That whitelisting is really great.

I prefer to add details:

  ... if the local IP address has been whitelisted 
+ in Security Controls / Network Access.

(I would like to add some authentication method without password and it will be able to run with minimal requirements one day.)

**Comment by jamescooke** [comment]
@hynekcer Cool. I've added that.

As I get more familiar with this module I can see that there's some space for some documentation. Had you ( @hynekcer @philchristensen ) got anywhere with that?

**Comment by philchristensen** [comment]
Thanks for the README fixes @jamescooke ; patches for any other documentation are always welcome!

**Comment by hynekcer** [comment]
Yes, thanks. I'm fully occupied by writing code that I can write documentation only for entirely new features. Then I must ask someone someone here to fix my English. I can answer some question to you or tell what is in development and that is better to prepare that text for the new version.

**Pull request merged**
