### PR TITLE
Use tox to multiplex tests on Travis

### PR DESCRIPTION
**Pull request by philchristensen**
At this point I'm incredibly close to having this working, just need a couple tips from @hynekcer to get it across the finish line. Right now it's basically working, but I'm getting an error for Django 1.4/Python 2.6:

```
py26dj14 runtests: commands[0] | /home/travis/build/django-salesforce/django-salesforce/.tox/py26dj14/bin/python manage.py test salesforce
Patched socket to IPv4 only
Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/build/django-salesforce/django-salesforce/.tox/py26dj14/lib/python2.6/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/travis/build/django-salesforce/django-salesforce/.tox/py26dj14/lib/python2.6/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/build/django-salesforce/django-salesforce/.tox/py26dj14/lib/python2.6/site-packages/django/core/management/commands/test.py", line 49, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/travis/build/django-salesforce/django-salesforce/.tox/py26dj14/lib/python2.6/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/travis/build/django-salesforce/django-salesforce/.tox/py26dj14/lib/python2.6/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/home/travis/build/django-salesforce/django-salesforce/.tox/py26dj14/lib/python2.6/site-packages/django/core/management/commands/test.py", line 72, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/travis/build/django-salesforce/django-salesforce/.tox/py26dj14/lib/python2.6/site-packages/django/test/simple.py", line 380, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "/home/travis/build/django-salesforce/django-salesforce/.tox/py26dj14/lib/python2.6/site-packages/django/test/simple.py", line 264, in build_suite
    suite.addTest(build_suite(app))
  File "/home/travis/build/django-salesforce/django-salesforce/.tox/py26dj14/lib/python2.6/site-packages/django/test/simple.py", line 79, in build_suite
    test_module = get_tests(app_module)
  File "/home/travis/build/django-salesforce/django-salesforce/.tox/py26dj14/lib/python2.6/site-packages/django/test/simple.py", line 36, in get_tests
    test_module = import_module('.'.join(prefix + [TEST_MODULE]))
  File "/home/travis/build/django-salesforce/django-salesforce/.tox/py26dj14/lib/python2.6/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/travis/build/django-salesforce/django-salesforce/salesforce/tests/__init__.py", line 6, in <module>
    from salesforce.tests.test_auth import *
  File "/home/travis/build/django-salesforce/django-salesforce/salesforce/tests/test_auth.py", line 14, in <module>
    from salesforce.tests.test_integration import default_is_sf
  File "/home/travis/build/django-salesforce/django-salesforce/salesforce/tests/test_integration.py", line 19, in <module>
    from salesforce.testrunner.example.models import (Account, Contact, Lead, User,
ImportError: cannot import name Attachment
ERROR: InvocationError: '/home/travis/build/django-salesforce/django-salesforce/.tox/py26dj14/bin/python manage.py test salesforce'
```

I'm thinking maybe this is because of a missing PyOpenSSL or something like that? Just a guess as I can't figure out the reason for that error...

Also, I had to make a couple changes to the tests.sh file, as I couldn't get the script to run correctly under bash or whatever passes for /bin/sh at Travis. I explicitly selected bash, and modified some operators to be more universal, but let me know if what I did no longer works for you.

Finally, although there's lots of reasons to use Tox, my original reason was because we couldn't run two sets of tests on a single django-salesforce instance at the same time. Is this no longer the case since ebe977fed? If so we can speed this up by doing separate runs for each environment.

### CODE REVIEW

**Comment by hynekcer** [comment]
The model "Test" is conditional and the model Attachment is also conditional, because it has a ForeignKey to "Test" in "example.models". The purpose is to test the relationships between builtin and custom models. You can fix the bug by a conditionaĺ import or by moving the import to corresponding test methods, that are still conditionally skipped.

Thanks and excuse that I omitted to do tests on infomplete databases and I left it on you. I am not at my computer.

**Comment by hynekcer** [comment]
Hurraaah, all branches green.

Master branch still has the advantage that it runs also the slow_test.py (that failed on RecordType previously)

**Comment by philchristensen** [comment]
This is great. I'm glad to make the fix to my SF org you describe [here](https://github.com/django-salesforce/django-salesforce/pull/129#issuecomment-139821706):

> The problem was not with QueueSobject but with RecordType object in your Salesforce.
> You can investigate which objects have record types in your SF (and you have access to these objects):  
>   Personal Setup / My Personal Information / Record Type Selection  
> Imagine that Contact has more RecordType and you want narrow the problem to some object:
>
>    $ python manage.py shell --settings=tests.inspectdb.settings
>    ```
>    from tests.inspectdb.models import RecordType
>    print([x.name for x in RecordType.objects.filter(sobject_type='Contact')])
>    ```

But I can't seem to find this area within SFDC, and even still, I'm not clear on what I specifically need to do to update my org.

**Comment by hynekcer** [comment]
I see it with my own eyes that other organization (new clean) can have a complete different menu where I can find nothing what I know, neither Search doesn't find it. Even "Setup" is a directly on the homepage a not under My Name submenu.

I tried tests on a completely new our SF organization and I found other issues that I'm fixing, but nothing similar to your problem.

Please try this

    >>> from django.db import connections
    >>> cur = connections['salesforce'].cursor()
    >>> cur.execute("SELECT Count(*) FROM RecordType")
    >>> cur.fetchone())
    [????]
    >>> cur.execute("SELECT Id, Name FROM RecordType")
    >>> for x in cur.fetchall():
    ...     print(x['Id'], x['Name'])

**Pull request merged**
