### PR TITLE
Cumulative change: Queries based on more ForeignKeys to the same table etc

### PR DESCRIPTION
**Pull request by hynekcer**
This is a cumulative pull request with finished more than a half of my development since November.

- It is possible to write filters with more foreign keys related to the same model..
- More compatibility with standard Django + migrations (no real migrations, but very useful if the development is done on any standard Django database), serializable default values etc.
- Improved introspection, supported DEFAULTED_ON_CREATE, better comments to exported models, complete compatibility betwen Python 2 and 3.
- Fixed SSL protocol settings to current security requirements

### CODE REVIEW

**Comment by hynekcer** [comment]
Everything from [Draft release notes](https://github.com/django-salesforce/django-salesforce/releases/tag/untagged-260e82c4b8aae5cf3d95) is also committed here. (I removed today obsoleted links to commit numbers because they have been reorganized since that.

**Comment by philchristensen** [comment]
This all looks great. It passed all my tests okay as well.

This seems like a pretty large amount of important updates (especially the SSL ones), worth making a 0.6 release. Do you agree, @hynekcer ?

**Comment by hynekcer** [comment]
A new version can be released soon e.g. next friday, but still without changing the whitespace everywhere. I still have aproximately fourty useful unmerged commits in seven branches. I should review them, combine the best together in a right order, to write tests for them and to begin to be sure it's so the right way. It will take about to the middle of July until I find slowly enough leisture time.

**Comment by philchristensen** [comment]
that makes sense. glad to wait on the white space change, as it obviously affects only a tiny number of users.

**Pull request merged**
