### PR TITLE
Decorator expectedFailureIf and much more

### LINKED ISSUE #116: @override_settings doesn't play nicely with SALESFORCE_DB_ALIAS setting
In attempt to balance both completeness and speed, I have some tests which use a local datastore and some which reach out to Salesforce. I try to keep the Salesforce tests small -- just enough to test all of the required core functionality -- and then rely on the local datastore for testing more complex behavior. (This also helps with API usage limits.)

The natural way to do this is would seem to be with the `@override_settings(SALESFORCE_DB_ALIAS='')` decorator -- use this to set the salesforce db to the remote datastore *only* for connectivity tests, and leave it set to a local datastore the rest of the time.

I was coming up against a strange bug where column Ids weren't being set correctly. After some thinking and sleuthing, I found that at least part of the problem lies with how database alias-checking is done in django-salesforce: there are places where the alias is checked on load, and then never again (ie live changes won't affect it). Thus, any updating of the `settings` isn't going to be reflected (I assume this is copy-by-value).

I'll make up a pull request to demonstrate what I mean by this.

### PR DESCRIPTION
**Pull request by hynekcer**
This PR is a set of fixes for new soft versions (tried on a new system), improved tests, refactored code, added comment, but nothing worthy of public attention.

- Fixed tests without conditional models. #128
- Fixed tox.ini for Django 1.4 with pip 7.0.0 (if works with Django 1.4.22; or with disabled wheels)
- Fixed depracation warnings with new `requests`
- Refactored some frequently repeated code, expecially imports
- Removed all static "sf_alias" from the backend. Fixed #116 (It can be considered safe)
- Implemented conditional decorator expectedFailureIf. It is used with known failing tests with Django 1.8. If the environment variable `QUIET_DJANGO_18=on` (or any habitual true value) is set then these testst are counted only as "expected failures" or "unexpected success" without noise, useful for tox.
- Fixed QuerySet.raw with empty result for Django 1.8.4+
- Removed some unused code
- Fixed one test for better accidental concurrency
- Fixed silent regressions in tests: made independent on SF_PK value again, no delay by connecting to SFDC in simple unit tests, without reconfiguring anything

This may be easily merged into `run-tox-on-travis` also.

### CODE REVIEW

**Comment by philchristensen** [comment]
This error looks like I need to create the "QueueSobject" custom object, is that correct?

Product2 * (write) 
Product2Feed 
Product2History 
Profile * 
PushTopic 
QueueSobject 
Error (debug details) [{"message":"An unexpected error occurred. Please include this ErrorId if you contact support: 2124805270-80145 (-1722456065)","errorCode":"UNKNOWN_EXCEPTION"}]
{'cookies': <RequestsCookieJar[]>, '_content': '[{"message":"An unexpected error occurred. Please include this ErrorId if you contact support: 2124805270-80145 (-1722456065)","errorCode":"UNKNOWN_EXCEPTION"}]', 'headers': {'date': 'Mon, 31 Aug 2015 19:01:06 GMT', 'transfer-encoding': 'chunked', 'content-type': 'application/json;charset=UTF-8', 'sforce-limit-info': 'api-usage=187/15000'}, 'url': u'https://na15.salesforce.com/services/data/v34.0/sobjects/RecordType/012i0000000tdzCAAQ', 'status_code': 500, '_content_consumed': True, 'encoding': 'UTF-8', 'request': <PreparedRequest [PATCH]>, 'connection': <salesforce.backend.adapter.SslHttpAdapter object at 0x7f0bc2828650>, 'elapsed': datetime.timedelta(0, 0, 134724), 'raw': <requests.packages.urllib3.response.HTTPResponse object at 0x7f0bc100ca10>, 'reason': 'Server Error', 'history': []}
Rollback is not implemented.
************** RecordType {u'errorCode': u'UNKNOWN_EXCEPTION', u'message': u'An unexpected error occurred. Please include this ErrorId if you contact support: 2124805270-80145 (-1722456065)'}

**Comment by philchristensen** [comment]
Also, the Pytohn 2.6 tests on the tox-based branch seem much closer:

```
======================================================================
ERROR: test_under_downgrade_attack_to_ssl_3 (salesforce.tests.test_ssl.SslTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/django-salesforce/django-salesforce/salesforce/tests/test_ssl.py", line 83, in test_under_downgrade_attack_to_ssl_3
    raise Exception("The protocol SSLv3 should be disabled for better security "
Exception: The protocol SSLv3 should be disabled for better security if possible. (It is disabled on all new systems.) see README
======================================================================
FAIL: test_aggregate_query (salesforce.tests.test_integration.BasicSOQLRoTest)
Test for different aggregate function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/django-salesforce/django-salesforce/salesforce/tests/test_integration.py", line 404, in test_aggregate_query
    self.assertDictEqual(result, {'UnitPrice__sum': 180, 'UnitPrice__count': 2, 'UnitPrice__avg': 90.0, 'UnitPrice__min': 80})
AssertionError: {'UnitPrice__sum': Decimal('360.0'), 'UnitPrice__count': 4, 'UnitPrice__avg': 90 [truncated]... != {'UnitPrice__sum': 180, 'UnitPrice__count': 2, 'UnitPrice__avg': 90.0, 'UnitPric [truncated]...
  {'UnitPrice__avg': 90.0,
-  'UnitPrice__count': 4,
?                      ^
+  'UnitPrice__count': 2,
?                      ^
-  'UnitPrice__min': Decimal('80.0'),
?                    ---------  ----
+  'UnitPrice__min': 80,
-  'UnitPrice__sum': Decimal('360.0')}
+  'UnitPrice__sum': 180}
----------------------------------------------------------------------
Ran 68 tests in 32.907s
```

The first error looks like a config issue I need to address in the travis confi, but what about the second one?

**Comment by hynekcer** [comment]
I don't see any error with QueueSobject. Can you reproduce it? Do you have administator permissions?

I use this in localsettings.py

    import ssl
    if sys.version_info >= (2, 7, 9):
        SF_SSL = {'ssl_version': ssl.PROTOCOL_SSLv23, 'skiptest_tls_11': False}
    else:
        SF_SSL = {'ssl_version': ssl.PROTOCOL_TLSv1, 'skiptest_tls_11': True}

Should it be put into settings.py in the repository?

Try to delete products with the name "test *". You have them doubled with products from some old test.

**Comment by philchristensen** [comment]
Sorry for the delays on dealing with this, but I'll definitely get to it this weekend.

**Comment by hynekcer** [comment]
I fixed automaic tests myself by simplifying them a little, without waiting for consent because a Travis test failing regularrly can't warn clear enough about unexpected problems.

The problem was not with QueueSobject but with RecordType object in your Salesforce.
You can investigate which objects have record types in your SF (and you have access to these objects):  
  Personal Setup / My Personal Information / Record Type Selection  
Imagine that Contact has more RecordType and you want narrow the problem to some object:

    $ python manage.py shell --settings=tests.inspectdb.settings
    Python ...
    >>> from tests.inspectdb.models impor RecordType
    >>> print([x.name for x in RecordType.objects.filter(sobject_type='Contact')])

**Comment by philchristensen** [comment]
Thanks very much!

**Pull request merged**
