### PR TITLE
Preparing version 1.1

### LINKED ISSUE #164: Status code 413 'Error: Request Entity Too Large: head'
When querying the Account standard object that has 400 custom fields on the object.  this creates an inconsistent error retrieving data for the django-salesforce module.  Is there any feedback or strategies on how to approach this?  It seems like a request size limitation on the salesforce side. Any suggestions or feedback would help.

### PR DESCRIPTION
**Pull request by hynekcer**
A vision: first only a new branch after some days to master and then a release after short waiting for feedback. No new code now if no new issue.

Changelog
-----------------
* Fix: Allow SOQL query up to 100000 characters, fixed #164
* Add: Support for custom authentication modules configurable by
  ``settings.DATABASES['salesforce']['AUTH']``
* Add: Authentication by Salesforce DX CLI application for developers, e.g. 'salesforce.auth.SfdxOrgWebAuth'
* Fix: Easier dynamic authentication. It requires an explicit setting now:
  ``"salesforce": {... "AUTH": "salesforce.auth.DynamicAuth" ...}``
* Add: Configurable API_VERSION by settings.DATABASES['salesforce']['API_VERSION']
* Add: A method .sf() on querysets and managers to can pass additional parameter
  e.g. all_or_none=True or edge_updates=True to bulk_create() and update() methods.
* Fix: Fixed long delay in application after unstable nework connection #267
* Fix: Queryset with empty slice e.g. queryset[100:100]
* Fix: Fix "max_length" in inspectdb for Choice Fields, because it is ignored
  by SFDC, but important for Django.

### CODE REVIEW

**Comment by philchristensen** [comment]
i'm not sure why 02b0c998 isn't being tested by travis, but I merged anyway.

**Comment by philchristensen** [comment]
Seems like it's just some kind of ordering bug in the GitHub UI. We're good.

**Comment by hynekcer** [comment]
Maybe I have pushed the last commit at the same time when the test of older head started,

**Comment by philchristensen** [comment]
I was thinking it looked like an issue at the SFDC end, as my last build attempt looks like it timed out, and the actual errors look like temporary ones. Was going to just try the build again today.

**Comment by hynekcer** [comment]
If "tox" would start then we would see the lines about dependencies list and install, but this looks really like the test has been cancelled before it started.

**Comment by philchristensen** [comment]
Looks like the run I started finished okay. I’m pretty sure it was just a bug in travis or SFDC or something, it’s fine now

**Comment by hynekcer** [comment]
It was a fortunamte random failure. I tested it again yesterday when I travelled through the valleys and the forest (average ping > 1s, packet lost 10%) and I found  by reading the log that commits b1451341 and f88ef2b9 (in v0.9) amplify the problems with this type of connection.

I have committed a short fix 249698a7 now directly to master.

**Comment by philchristensen** [comment]
It’s really great that you’re able to generate such detailed interaction metrics. Let me know if there’s anything I can do to help.

**Pull request merged**
