### PR TITLE
Resolve BaseDatabaseXXX import errors under Django 1.8

### LINKED ISSUE #99: Incompatibility with Django 1.8
Per Django 1.8 docs: 

    ### Database backend API

    The following changes to the database backend API are documented to assist those writing third-party backends in updating their code:

    BaseDatabaseXXX classes have been moved to django.db.backends.base. Please import them from the new locations:

I am working on a patch for this. Looks to be a simple fix of switching imports out.

### PR DESCRIPTION
**Pull request by naoyak**
Resolves #99. The import order becomes a bit messy - let me know if this works or not.

### CODE REVIEW

**Comment by philchristensen** [comment]
Thanks for this submission. I'm expecting to get it reviewed and merged this weekend.

**Comment by philchristensen** [comment]
I think there might be some (seemingly non-error causing) whitespace issues in there, but I'll take care of them, hopefully by just going ahead with #101

**Comment by hynekcer** [comment]
Whitespace isuue is only on two lines that I simply fixed. More unpleasant is the merge from too old code v0.4 that makes the commit history confused. I fixed it by "git rebase". I am writing a fix for tests for the recent code Lead convert # 96. I expect my pull request today, including Naoyak's code.

**Comment by naoyak** [comment]
@hynekcer @philchristensen does that look better now? Sorry, my git skills are still rudimentary.

**Comment by hynekcer** [comment]
Yes, your code is now perfect and I use it as the first step. I can't run django-salesforce with Django 1.8 yet. It is normal that every new Django version requires some deep fixes.

**Comment by hynekcer** [comment]
I used your pull request in my #102 which solves more related problems with Django 1.8, but not all. Maybe it is enough for you. More info in my Readme.

**Pull request merged**
