### PR TITLE
Preparing version 0.6.9

### PR DESCRIPTION
**Pull request by hynekcer**
I think a release before 0.7 is necessary (before the complete support for Django 1.10)

Info:
[Support Django 1.10 - part way](https://github.com/django-salesforce/django-salesforce/releases/edit/untagged-e6515306fe07f94e6b0e) release notes - draft

Dynamic fields copied from a models_template (inspectdb) and combined with normal models. [my blog style description](https://github.com/hynekcer/django-salesforce/wiki/Dynamic-fields)

It can be read better by commits and commit messages (frequently multiline messages). I expressed my [coding style for this project](https://github.com/hynekcer/django-salesforce/wiki/Contributing) that can be useful for reading.

---

(I have still 750 lines after version 0.6.9, the version 0.7 seems realistic. The most important is a cursor compliant with Python DB API 2. It is necessary because the rows in ValuesQueryset are converted to list. The cursor must include a description of columns and it is possible that some related column is never present before 2000-th line. Therefore I parse the SOQL query.)

### CODE REVIEW

**Comment by philchristensen** [comment]
So, just to be clear, this branch is ready for merge and release as 0.6.9? Or do you still have some revisions I should wait for?

**Comment by hynekcer** [comment]
It can be just merged now. I appreciate some your revision or comment. The release can wait one day if no regression is found.

**Comment by philchristensen** [comment]
The tests didn't really fail, but it looks like Travis CI doesn't yet have an interpreter for Python 3.5. Do I just take "py35-dj110" out of the `envlist` param, or should it be replaced by something that tests Django 1.10 on another Python?

**Comment by hynekcer** [comment]
Travis can test also with Python 3.5 (https://docs.travis-ci.com/user/languages/python), but it is not necessary.
You can write any combination of Python and Django with the new tox.ini in .travis.yml at the last line, e.g.

    tox -r -e py27-dj17,py34-dj18,py27-dj19,py34-dj110

I prefer not to change the default envlist due to Travis.
Maybe if you write

    language: python
    python:
        "3.5"

this version will be added, the tox will start under python3.5 and the default installed versions 2.7 and 3.4 could be also found.

**Comment by philchristensen** [comment]
Hmm, that's strange, I definitely got:

`ERROR:   py35-dj110: InterpreterNotFound: python3.5`

This may be because of some issues at Travis: https://www.traviscistatus.com/incidents/2p40l49r3yxd

I'll try again a bit later.

**Comment by philchristensen** [comment]
Still having issues getting the test to run in Python 3.5, so I sent an email to Travis support.

**Comment by hynekcer** [comment]
Can you retry Travis please, with the new commit for explicit Python 3.5? If it fails, the line above for specific versions can be added to Travis configuration. If 3.5 would be a problem on your localhost, it is a serious reason, otherwise I prefer not to remove 3.5 from an easy "everyday" test.

Do you think something to add to README?

**Comment by philchristensen** [comment]
Don't worry, I'm not trying to change anything just to fit Travis. I just didn't want to merge this while Travis was having issues because it would show as "build: failed" on the little button graphic.

I'm going to update the README as a separate commit after getting this merged. Nothing major, just some small wording changes.

**Comment by philchristensen** [comment]
Ugh, shit. I didn't want to squash merge that.

**Comment by philchristensen** [comment]
I merged locally and did a force push to undo my squash merge, so your history is preserved.

**Pull request merged**
