### PR TITLE
Fixed a rough support for Django 1.8

### PR DESCRIPTION
**Pull request by hynekcer**
The pull request #100 is included here, but it was not enough to pass even 1% of tests with Django 1.8. One branch are Naoya Kanai's and my fixes to pass 80 % of tests. Other branch are fixes to pass all test in master with Django 1.7 before anything changed. After the merge I fixed the .count() method with Django 1.8 and the Readme. Six tests are still failing with Django 1.8 as noted in Readme.

### CODE REVIEW

**Comment by philchristensen** [comment]
I'm open to ideas on how to deal with this. I'm glad to merge it now if you think it's better with partial support in master than none, being that Django 1.8 is the current release.

**Comment by hynekcer** [comment]
I think also it is better to merge it. I added a RuntimeWarning for Django 1.8 currently. Maybe you can push it at pypi as e.g. 0.5.1. after grammar editing in docs.

Why: An old version on pypi that fails without a clear message is a very bad user experience. Packages from pypi are usually updated automatically without reading the new docs until a problem is encountered. A setup and requirements.txt that could silently downgrade Django to 1.7.x is evenso bad.

**Comment by philchristensen** [comment]
That sounds good to me, I had missed the RuntimeWarning addition, and agree that's better.

**Comment by hynekcer** [comment]
That RuntimeWarning was after your reflection as my answer to it.

**Comment by philchristensen** [comment]
Oh, good! ;-)

**Comment by tvanesse** [comment]
I understand 4fbfa0a is not yet pushed on Pypi, is it? I've got 0.5 installed here but I still can't get Django>=1.8 started (because of #99 ). Are you waiting for a full support before releasing the latest version?

**Comment by philchristensen** [comment]
Sorry, that's on me. I'll get 0.5.1 released ASAP, but in the meantime, you could use `pip` to install the upcoming release directly from this repo.

    pip install git+ssh://git@github.com/django-salesforce/django-salesforce.git@4fbfa0a7#egg=django-salesforce

There's more detail on using `pip` this way here: https://pip.pypa.io/en/latest/reference/pip_install.html#git

**Comment by tvanesse** [comment]
Awesome. Didn't know `pip` could do this kind of thing. Thanks for that :blush:

**Comment by tvanesse** [comment]
Hum... It works great locally but Heroku's `pip` is super stupid and won't understand the new dependency definition generated by `pip freeze`. More precisely, `pip` complains it can't find any suitable version for `django-salesforce==0.5-30-g4fbfa0a` from my new `requirements.txt` (I mean, the `pip` run on Heroku). I am not sure of how they deal with their virtual environments, but running `pip install xxx --upgrade` with their CLI won't actually install the package, it will stubbornly stay at 0.5.

**Comment by philchristensen** [comment]
Usually when I run on Heroku or other platforms I don't entirely control, I usually start my deploy process with:

    pip install -U pip

Still, I will do that release as soon as I can. It's just that I foolishly only have the PyPI credentials at home,  so I need to do it from there, and I keep forgetting. No good excuse, I know ;-)

**Comment by tvanesse** [comment]
> It's just that I foolishly only have the PyPI credentials at home, so I need to do it from there, and I keep > forgetting. No good excuse, I know ;-)

That sounds like a good excuse to me :smile:  It's open-source after all. Your involvement is already much appreciated.

**Comment by naoyak** [comment]
@philchristensen should be a separate issue perhaps, but related problem when I try to `pip install` from master:
```
Collecting https://github.com/django-salesforce/django-salesforce/zipball/master (from -r requirements.txt (line 48))
  Downloading https://github.com/django-salesforce/django-salesforce/zipball/master (97kB)
    100% |████████████████████████████████| 98kB 3.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-gUg3Iw-build/setup.py", line 95, in <module>
        dist = autosetup()
      File "/tmp/pip-gUg3Iw-build/setup.py", line 72, in autosetup
        version			= get_tagged_version(),
      File "/tmp/pip-gUg3Iw-build/setup.py", line 49, in get_tagged_version
        raise RuntimeError(stderrdata)
    RuntimeError: fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by hynekcer** [comment]
I must confirm naoyak's issue. This is due to very DRY version numbering of the project that depends only on git tags and the version number is nowhere written in the source, except the readme file. This is perfect, but this can not work with the snapshots downloaded by the Github button "Download ZIP". What do you mean @philchristensen ?

**Comment by philchristensen** [comment]
Oh, I see why that wouldn't work. I think I have a fix for that, but first I will get these recent pull requests merged and released.

**Comment by philchristensen** [comment]
I just pushed 0.5.1 to PyPI. It's probably a pretty short-lived release, as 0.6 is right around the corner...

**Comment by tvanesse** [comment]
Great. Thanks @philchristensen

**Pull request merged**
