### PR TITLE
Fixed support for Salesforce 45.0 Spring '19 and fixed inspectdb

### PR DESCRIPTION
**Pull request by hynekcer**
Some bugs in inspectdb are fixed now. The most important is caused by simplified sobject describe in the new Salesforce 45.0 Spring '19, currently known in Preview sandboxes. I think that it is a reason for a new version 0.8 now.

The version 45.0 works fine now even with API 45.0, but the compatible API 44.0 is configured in master until all instances migrate.

### CODE REVIEW

**Comment by hynekcer** [comment]
I going to add something today.

**Comment by hynekcer** [comment]
Please commit it. A new pull request will depend on it.

**Comment by philchristensen** [comment]
Looks like a small issue with respect to the "id" field. My test account still uses "Id".

**Comment by philchristensen** [comment]
I did merge in #223 because it was a small one, so it's probably also worth rebasing.

**Comment by hynekcer** [comment]
All these commits are a part of a longer PR #222 that has been merged yesterday.

**Pull request closed without merging**
