### PR TITLE
Many2many relationship, advanced Where conditions

### PR DESCRIPTION
**Pull request by hynekcer**
- Implemented Many2many realtionship so that the related name .all() and the reverse related name .all() works, with Django 1.4 to 1.8

- Speed up tests. The connection to SFDC is not created until necessary, because some tests don't require the connection at all.

closes #103, #124

### CODE REVIEW

**Comment by philchristensen** [comment]
Wow! Great stuff.

**Comment by philchristensen** [comment]
I'm having some issues with the tests on Travis, but they all appear related to the fact that I ended up running two builds at once because of two merges right in a row. I'll fix the tests ASAP.

**Comment by hynekcer** [comment]
The object `django_Test__c` is the model `example.models.Test`. It is really a bug that the test is not skipped. I recommend to create soon if you want to test relationships between custom and builtin objects (in the future, currently it is skipped because wuold fail) It is currently the only custom object that is really tested on SFDC. (custom object `ChargentOrders__ChargentOrder__c` is "mocked")

**Comment by philchristensen** [comment]
Thanks for your help. Tests are passing fine on the Travis build now.

**Pull request merged**
