### PR TITLE
fixed #175 also for foreign keys with null values

### LINKED ISSUE #175: Issues and limitations around `select_related` usage
## Context
We're attempting to reduce our overall network calls to SFDC. We are trying to do this by using `select_related()` to prefetch related objects associated to the model in our queryset.

## Example
For example, lets attempt to iterate over all `Opportunities` in our SFDC instance. For each `Opportunity`, print the associated opp owner (which is an `User` object). Assume the model definition below:

**models.py:**

```python
from salesforce.models import SalesforceModel

class SFDCUser(SalesforceModel):
    """Access to the SFDC `User` table."""
    username = models.CharField(max_length=80)

    class Meta(SalesforceModel.Meta):
        db_table = 'User'

class Opportunity(SalesforceModel):
    """Access to the SFDC `Opportunity` table."""
    owner = models.ForeignKey('SFDCUser', custom=False, db_column=u'OwnerId')
  
    class Meta(models.Model.Meta):
        db_table = 'Opportunity'
```

**query.py:**

```python
# Fetch each opp while joining on owner to avoid subsequent calls to 
# get owner by id for each iteration.
for opp in Opportunity.objects.all().select_related('owner'):
    print opp.owner

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-91-bdc76891f5b9> in <module>()
----> 1 for o in opp:
      2     print o
      3     print o.owner
      4

/usr/local/etc/virtualenvs/gears/local/lib/python2.7/site-packages/django/db/models/query.pyc in __iter__(self)
    256                - Responsible for turning the rows into model objects.
    257         """
--> 258         self._fetch_all()
    259         return iter(self._result_cache)
    260

/usr/local/etc/virtualenvs/gears/local/lib/python2.7/site-packages/django/db/models/query.pyc in _fetch_all(self)
   1072     def _fetch_all(self):
   1073         if self._result_cache is None:
-> 1074             self._result_cache = list(self.iterator())
   1075         if self._prefetch_related_lookups and not self._prefetch_done:
   1076             self._prefetch_related_objects()

/usr/local/etc/virtualenvs/gears/local/lib/python2.7/site-packages/salesforce/backend/query.pyc in iterator(self)
    235         """
    236         try:
--> 237             sql, params = SQLCompiler(self.query, connections[self.db], None).as_sql()
    238         except EmptyResultSet:
    239             raise StopIteration

/usr/local/etc/virtualenvs/gears/local/lib/python2.7/site-packages/salesforce/backend/compiler.pyc in as_sql(self, with_limits, with_col_aliases, subquery)
    172                     if soql_trans and re.match(r'^\w+\.\w+$', s_sql):
    173                         tab_name, col_name = s_sql.split('.')
--> 174                         s_sql = '%s.%s' % (soql_trans[tab_name], col_name)
    175                     params.extend(s_params)
    176                     out_cols.append(s_sql)

KeyError: u'Owner'
```

Perhaps I'm doing this incorrectly; perhaps a bug. Any help would be greatly appreciated :)

### PR DESCRIPTION
**Pull request by hynekcer**

### CODE REVIEW

**Comment by cooncesean** [comment]
I feel like such a pester but was wondering if you guys had any intention of cutting a formal release for this? If not, no worries - I'm fine working off of the commit sha.

Thank you one more time for the awesome support :)

**Comment by philchristensen** [comment]
I think we'll be doing a release once #179 is merged and confirmed. Since it drops support for Django 1.7, we'll be going to 0.7.0.

@hynekcer: I can do a release in the next couple days, or wait if you've got imminent merges. I'm also fine with releasing now and pushing out 0.7.1 later.

**Comment by hynekcer** [comment]
It is still about 18 commits before the standard support of Django 1.10 announced as the target of 0.7, however any release is important soon, it was also announced 0.6.9 is the last that supports Django 1.7 a  and simple_select_related is a useful feature that can be in release notes..

**Comment by philchristensen** [comment]
Oh, okay, I forgot how we had specified the EOL for 1.7.

In that case, I can do a 0.6.10 release to push these changes out. I'll be merging #179 shortly, and will do the release in the next day or two.

**Pull request merged**
