### PR TITLE
Some fixes for Django 1.8, Tests for SSL, filter with similar FK etc

### PR DESCRIPTION
**Pull request by hynekcer**
Much documentation together with code

If the test of TLS 1.1+ fails and no upgrade is possible, it can be skipped by
settings.py

       SF_SSL = {'skiptest_tls_11': True, ...}

### CODE REVIEW

**Comment by philchristensen** [comment]
I'm seeing two relatively minor test failures:
t

**Comment by philchristensen** [comment]
I see one of them is a config issue in my Travis setup...

**Comment by hynekcer** [comment]
The second can be fixed by settings.py

    SF_SSL = {'ssl_version': ssl.PROTOCOL_SSLv23}

**Comment by philchristensen** [comment]
Yep, just added that. It looks like the first is trivial as well. I'll make a PR for the hotfix.

**Pull request merged**
