### PR TITLE
Tooling API and Metadata API

### PR DESCRIPTION
**Pull request by hynekcer**
Implemented Tooling API: creating Apex classes, running Apex, reading ApexLog.

Example: Enable logging 5 minutes with minimalistic levels and run Hello World.

```
$ python manage.py shell
>>> from salesforce.tooling import *
>>> user_id = sf_get('')['identity'].split('/')[-1]
>>> set_trace_flag(user_id, user_id, level='Debug', ApexProfiling='Warn', System='Warn')
>>> result, log_info, log_body = execute_anonymous_logged("System.debug('Hello'+' World');")
>>> assert 'Hello World' in log_body
```

More examples in docs strings after ">>>".

---

Implemented a simple Metadata API with demo that creates a 'Test__c' object.

```
$ python manage.py shell
>>> from salesforce.tooling import *
>>> install_metadata_service()
>>> create_demo_test_object()
```

The function 'install_metadata_service' installls a 750 kB class
'MetadataService' from Github to SF. This implementation requires enabled
callouts from your SF site to itself. You will be informed how to do it,
if it fails.

---

I expect merge into a new branch and discussion about it until it will be really used. It is currently only a nice tool more useful for me than the Developer Console.

The old merged branch "debug-silent-fix" can be deleted.

### CODE REVIEW

**Comment by philchristensen** [comment]
When I try to install the demo test object, I get a failure trying to install the metadata service:

Error (debug details) [{"message":"duplicate value found: <unknown> duplicates value on record with id: <unknown>","errorCode":"DUPLICATE_VALUE","fields":[]}]
{'cookies': <<class 'requests.cookies.RequestsCookieJar'>[]>, '_content': '[{"message":"duplicate value found: <unknown> duplicates value on record with id: <unknown>","errorCode":"DUPLICATE_VALUE","fields":[]}]', 'headers': {'date': 'Sat, 08 Aug 2015 16:37:09 GMT', 'transfer-encoding': 'chunked', 'content-type': 'application/json;charset=UTF-8', 'sforce-limit-info': 'api-usage=2360/15000'}, 'url': u'https://na15.salesforce.com/services/data/v34.0/tooling/sobjects/ApexClass', 'status_code': 400, '_content_consumed': True, 'encoding': 'UTF-8', 'request': <PreparedRequest [POST]>, 'connection': <salesforce.backend.adapter.SslHttpAdapter object at 0x106aa0090>, 'elapsed': datetime.timedelta(0, 25, 943721), 'raw': <requests.packages.urllib3.response.HTTPResponse object at 0x106ac3250>, 'reason': 'Bad Request', 'history': []}

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/phil/Workspace/django-salesforce/salesforce/backend/tooling.py", line 269, in install_metadata_service
  File "/Users/phil/Workspace/django-salesforce/salesforce/backend/tooling.py", line 109, in sf_post
  File "/Users/phil/Workspace/django-salesforce/salesforce/backend/query.py", line 150, in handle_api_exceptions
    raise base.SalesforceError('%s' % data, data, response, verbose)
SalesforceError: {u'errorCode': u'DUPLICATE_VALUE', u'fields': [], u'message': u'duplicate value found: <unknown> duplicates value on record with id: <unknown>'}
```

**Comment by philchristensen** [comment]
You can disregard my erroneous comment.

**Comment by philchristensen** [comment]
Eh, it might have been correct after all. I can't really figure out what happened, but the first time I ran it, I had a failure installing the metadata service. I was on the wrong branch, but in this case I think it was using the pyc file left over, as the tooling.py file doesn't exist in master. This was the error I got:

Error (debug details) [{"message":"duplicate value found: <unknown> duplicates value on record with id: <unknown>","errorCode":"DUPLICATE_VALUE","fields":[]}]
{'cookies': <<class 'requests.cookies.RequestsCookieJar'>[]>, '_content': '[{"message":"duplicate value found: <unknown> duplicates value on record with id: <unknown>","errorCode":"DUPLICATE_VALUE","fields":[]}]', 'headers': {'date': 'Sat, 08 Aug 2015 16:37:09 GMT', 'transfer-encoding': 'chunked', 'content-type': 'application/json;charset=UTF-8', 'sforce-limit-info': 'api-usage=2360/15000'}, 'url': u'https://na15.salesforce.com/services/data/v34.0/tooling/sobjects/ApexClass', 'status_code': 400, '_content_consumed': True, 'encoding': 'UTF-8', 'request': <PreparedRequest [POST]>, 'connection': <salesforce.backend.adapter.SslHttpAdapter object at 0x106aa0090>, 'elapsed': datetime.timedelta(0, 25, 943721), 'raw': <requests.packages.urllib3.response.HTTPResponse object at 0x106ac3250>, 'reason': 'Bad Request', 'history': []}

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/phil/Workspace/django-salesforce/salesforce/backend/tooling.py", line 269, in install_metadata_service
  File "/Users/phil/Workspace/django-salesforce/salesforce/backend/tooling.py", line 109, in sf_post
  File "/Users/phil/Workspace/django-salesforce/salesforce/backend/query.py", line 150, in handle_api_exceptions
    raise base.SalesforceError('%s' % data, data, response, verbose)
SalesforceError: {u'errorCode': u'DUPLICATE_VALUE', u'fields': [], u'message': u'duplicate value found: <unknown> duplicates value on record with id: <unknown>'}
```

I tried running create_demo_test_object() anyways, and got an error about a function not being iterable, and found this bug:

```diff
diff --git a/salesforce/backend/tooling.py b/salesforce/backend/tooling.py
index 1b00bff..70c44eb 100644
--- a/salesforce/backend/tooling.py
+++ b/salesforce/backend/tooling.py
@@ -368,7 +368,7 @@ def create_demo_test_object():

        handleSaveResults(service.createMetadata(new List<MetadataService.Metadata> { customField, customField2, customField3 }));
        """
-       if not 'django_Test__c' in sf_tables:
+       if not 'django_Test__c' in sf_tables():
                call_metadata_api(demo_apex_code)

        current_user = connections[sf_alias].settings_dict['USER']
```

In a subsequent attempt, the install_metadata_service() function seemed to run properly, but when I ran create_demo_test_object() I got an error about enabling callouts. I went ahead and followed the instructions, than ran create_demo_test_object() again. This resulted in:

{u'success': True, u'column': -1, u'compiled': True, u'compileProblem': None, 'elapsed': datetime.timedelta(0, 1, 273945), u'exceptionMessage': None, u'exceptionStackTrace': None, 'timestamp': datetime.datetime(2015, 8, 8, 16, 46, 32), u'line': -1}
prev: None
logs: []
({u'success': True, u'column': -1, u'compiled': True, u'compileProblem': None, 'elapsed': datetime.timedelta(0, 1, 273945), u'exceptionMessage': None, u'exceptionStackTrace': None, 'timestamp': datetime.datetime(2015, 8, 8, 16, 46, 32), u'line': -1}, None)
None
Error (debug details) [{"message":"duplicate value found: <unknown> duplicates value on record with id: <unknown>","errorCode":"DUPLICATE_VALUE","fields":[]}]
{'cookies': <<class 'requests.cookies.RequestsCookieJar'>[]>, '_content': '[{"message":"duplicate value found: <unknown> duplicates value on record with id: <unknown>","errorCode":"DUPLICATE_VALUE","fields":[]}]', 'headers': {'date': 'Sat, 08 Aug 2015 16:46:34 GMT', 'transfer-encoding': 'chunked', 'content-type': 'application/json;charset=UTF-8', 'sforce-limit-info': 'api-usage=3019/15000'}, 'url': u'https://na15.salesforce.com/services/data/v34.0/sobjects/FieldPermissions', 'status_code': 400, '_content_consumed': True, 'encoding': 'UTF-8', 'request': <PreparedRequest [POST]>, 'connection': <salesforce.backend.adapter.SslHttpAdapter object at 0x1074afd10>, 'elapsed': datetime.timedelta(0, 0, 217712), 'raw': <requests.packages.urllib3.response.HTTPResponse object at 0x1074c7050>, 'reason': 'Bad Request', 'history': []}

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/phil/Workspace/django-salesforce/salesforce/backend/tooling.py", line 420, in create_demo_test_object
    PermissionsEdit=True, PermissionsRead=True)
  File "/Users/phil/Workspace/django-salesforce/salesforce/backend/tooling.py", line 109, in sf_post
    return handle_api_exceptions(url, connection.sf_session.post, headers=headers, data=json.dumps(post_data))
  File "/Users/phil/Workspace/django-salesforce/salesforce/backend/query.py", line 150, in handle_api_exceptions
    raise base.SalesforceError('%s' % data, data, response, verbose)
SalesforceError: {u'errorCode': u'DUPLICATE_VALUE', u'fields': [], u'message': u'duplicate value found: <unknown> duplicates value on record with id: <unknown>'}
``` 

Now if I try to run the test, I get this error:

```
ERROR: test_simple_custom_object (salesforce.tests.test_integration.BasicSOQLRoTest)
Create, read and delete a simple custom object `django_Test__c`.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/django-salesforce/django-salesforce/salesforce/tests/test_integration.py", line 267, in test_simple_custom_object
    obj.save()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/travis/build/django-salesforce/django-salesforce/salesforce/backend/compiler.py", line 554, in execute_sql
    cursor.execute(sql, params)
  File "/home/travis/build/django-salesforce/django-salesforce/salesforce/backend/query.py", line 420, in execute
    response = self.execute_insert(self.query)
  File "/home/travis/build/django-salesforce/django-salesforce/salesforce/backend/query.py", line 478, in execute_insert
    return handle_api_exceptions(url, self.session.post, headers=headers, data=json.dumps(post_data), _cursor=self)
  File "/home/travis/build/django-salesforce/django-salesforce/salesforce/backend/query.py", line 141, in handle_api_exceptions
    raise base.SalesforceError(data['message'], data, response, verbose)
SalesforceError: No such column 'TestBool__c' on sobject of type django_Test__c
```

Which is especially odd because TestBool__c **does** appear to exist. The object is still missing the `Contact` lookup field, though.

Any ideas?

**Comment by hynekcer** [comment]
Look at www.SFDC / App Setup / Develop / Apex Classes / tab with letter "M"

If you see name "MetadataService" (800kB) you have the service installed

**Comment by hynekcer** [comment]
Hmm  "sf_tables()" is sue to the last optimization and tooling branch is not updated yet.

I don't know how you have permissions for field 'django_Test__c.TestText__c' yet, but you need other permissions. Comment out lines 408 - 410, 418 - 421 and run it again to do the rest or you can set permissions to new fields manually.

**Comment by hynekcer** [comment]
I am afraid that the tooling api will be not useful for production but for a sandbox it can be fast and good. What to do if a similar (duplicate) object exists or a similar permission to be safe and functional? I don't want to be responsible for SF permissions on productions sites at all.

**Comment by philchristensen** [comment]
I think that's a totally reasonable limitation.

-Phil
sent from my phone

**Comment by philchristensen** [comment]
Okay, this seems to be the most repeatable error now:

Error (debug details) [{"message":"Sobject Type Name: bad value for restricted picklist field: django_Test__c","errorCode":"INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST","fields":["SobjectType"]}]
{'cookies': <<class 'requests.cookies.RequestsCookieJar'>[]>, '_content': '[{"message":"Sobject Type Name: bad value for restricted picklist field: django_Test__c","errorCode":"INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST","fields":["SobjectType"]}]', 'headers': {'date': 'Sat, 08 Aug 2015 20:08:57 GMT', 'transfer-encoding': 'chunked', 'content-type': 'application/json;charset=UTF-8', 'sforce-limit-info': 'api-usage=5022/15000'}, 'url': u'https://na15.salesforce.com/services/data/v34.0/sobjects/ObjectPermissions', 'status_code': 400, '_content_consumed': True, 'encoding': 'UTF-8', 'request': <PreparedRequest [POST]>, 'connection': <salesforce.backend.adapter.SslHttpAdapter object at 0x10c0d16d0>, 'elapsed': datetime.timedelta(0, 0, 80837), 'raw': <requests.packages.urllib3.response.HTTPResponse object at 0x10c0eb810>, 'reason': 'Bad Request', 'history': []}

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/phil/Workspace/django-salesforce/salesforce/backend/tooling.py", line 424, in create_demo_test_object
    **dict.fromkeys(PERMISSION_NAMES, True))
  File "/Users/phil/Workspace/django-salesforce/salesforce/backend/tooling.py", line 109, in sf_post
    return handle_api_exceptions(url, connection.sf_session.post, headers=headers, data=json.dumps(post_data))
  File "/Users/phil/Workspace/django-salesforce/salesforce/backend/query.py", line 150, in handle_api_exceptions
    raise base.SalesforceError('%s' % data, data, response, verbose)
SalesforceError: {u'errorCode': u'INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST', u'fields': [u'SobjectType'], u'message': u'Sobject Type Name: bad value for restricted picklist field: django_Test__c'}
```

Now it's not creating the django_Test object at all.

**Comment by hynekcer** [comment]
Try it manually please. It is still much faster for such simple object. Thanks for your effort. I am working on the query compiler. That is a must

**Comment by philchristensen** [comment]
Okay, I'll see what I can do. I'm really operating on the edge of my Salesforce knowledge here ;-)

**Comment by philchristensen** [comment]
Oh, nevermind, that was much easier to do manually than I had thought.

**Comment by hynekcer** [comment]
Yes, you were faster :-)
Administration Setup / Permission Sets / Django Salesforce / Object Settings / django_Tests / Edit 
Check checkboxes that are not gray.

**Comment by hynekcer** [comment]
Closed. I will probably prefer Salesforce DX command line tool, that is popular.

**Pull request closed without merging**
