### PR TITLE
sensible version numbers in tox.ini

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
> I don't want to commit a new tox.ini at every first workday in the month. tox --recreate is much more viable to be run locally every month.

eh? you don't have to do that.

**Comment by graingert** [comment]
`~=X.Y.Z` is just equivalent to `>=X.Y.Z, ==X.Y.*` nothing to do with tox --recreate on the first workday.

**Comment by graingert** [comment]
@philchristensen this PR is ready to go. I'm not sure why it's not running on Travis though

**Comment by philchristensen** [comment]
I need to copy the branch into the main repo before it will run on Travis; it has to do with the encrypted SF credentials stored in the .travis.yml file. If you'd like to rebase this from master, you'll get the latest changes, then I can push it to this repo to have it tested.

**Comment by graingert** [comment]
@philchristensen I've re-based anyway

**Comment by graingert** [comment]
> having a more pedandic versioning scheme.

It's actually a less pedantic versioning scheme, django versions eg 1.11.100 are accepted.

**Comment by philchristensen** [comment]
Yeah, I get it. Using the ~= operator is a new one to me, but it seems to do what we want.

**Comment by hynekcer** [comment]
Can you please to send a link to docs to see that "~=" is a documented syntax? I can not find it on https://tox.readthedocs.io/ (Maybe it is / was an experimental feature.)

A problem is with new versions that has no patch release. (I want to complete the work on Django 2.0 support.) It is not matched by dependency "Django~=2.0.0" or "2.0.1" and it seems that a tox.ini with the dependency operator "~=" must be updated in January after 2.0.1. I prefer the classic syntax "Django>=2.0,<2.1".

**Comment by graingert** [comment]
You want `>=2.0.0, <3`

It's not documented in tox because it's a distutils feature. tox passes deps straight to pip install

**Pull request merged**
