### PR TITLE
support django 1.11

### PR DESCRIPTION
**Pull request by tuky**
might need improvements here and there and a little rough, but for us it is working.

### CODE REVIEW

**Comment by philchristensen** [comment]
We really appreciate the submission! Unfortunately this isn't passing tests for me on dj111 and dj18: 

https://travis-ci.org/django-salesforce/django-salesforce/builds/226877895

**Comment by hynekcer** [comment]
I also wrote a fix for Django 1.11 a few days before Easter. Then I tried to improve some feature in order to decide, which direction of development is better, to prevent not to announce something that must be redefined or removed soon. The pause during Easter and too much other work next week... A discussion would be probably useful if you or I would know on what it' working on and what burns also other people. I review it and accept probably very much.

**Comment by tuky** [comment]
@hynekcer Do you think you could extract only the 1.11 compatibilty fixes and only PR those or include them here? I think it is important to get that right, before changing other fundamental things. Unfortunately I don't have the knowledge of django db backends and 1.11 seems to have some bigger changes, e.g. due to the new explicit sub-queries.

**Comment by hynekcer** [comment]
Tuky@ thanks for your code, it is partly inspirative and it wold be very useful, but it has been solved still e.g. here https://github.com/hynekcer/django-salesforce/tree/tuky-fix-pr-182 As you see I accepted all your and Zee93 code except code that was reverted or fixed by you immediately. I will rename and reorganize my commits, but the result code passes all tests still. The only problem is in bulk update in non trivial cases, that is marked as expected failure now, if QUIET_KNOWN_BUGS is set.

**Comment by hynekcer** [comment]
A new PR #183 with many your code is ready. Especially your solution with back-ported Iterator class is very appreciated. My original solution was "defensive" to can not modify or break anything working still, even that new features were emulated on old ones. Your solution looks safe. Thanks very much.

**Pull request closed without merging**
