### PR TITLE
Fixed router bug with an alternate SF database. close #160

### LINKED ISSUE #160: Django 1.10: deferred_class_factory no longer exists
After (accidentally) upgrading to Django 1.10, I got a failure in `manage.py migrate` due to a broken import:

```
+ python manage.py migrate --noinput
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/management/base.py", line 353, in execute
    self.check()
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/checks/model_checks.py", line 30, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/db/models/base.py", line 1266, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/db/models/base.py", line 1337, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 893, in check
    errors = super(AutoField, self).check(**kwargs)
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 208, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 310, in _check_backend_specific_checks
    if router.allow_migrate(db, app_label, model_name=self.model._meta.model_name):
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/db/utils.py", line 300, in allow_migrate
    allow = method(db, app_label, **hints)
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/salesforce/router.py", line 87, in allow_migrate
    if is_sf_database(db):
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/salesforce/router.py", line 23, in is_sf_database
    from salesforce.backend.base import DatabaseWrapper
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/salesforce/backend/base.py", line 31, in <module>
    from salesforce.backend.introspection import DatabaseIntrospection
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/salesforce/backend/introspection.py", line 24, in <module>
    from salesforce.backend import compiler, query
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/salesforce/backend/query.py", line 25, in <module>
    from django.db.models.query_utils import deferred_class_factory
ImportError: cannot import name deferred_class_factory
```

I haven't had a moment to investigate it closer to see if deferred_class_factory has just moved to another module. Sooner or later I know we might run into issues with all the various changes in the Django ORM since 1.8 and have some issues.

### PR DESCRIPTION
**Pull request by hynekcer**
(Maybe I add a commit here with tests and docs, but I want to show a solution that has been well tested manually. Wait same days with merge.)

### CODE REVIEW

**Comment by hynekcer** [comment]
I'm thinking about to remove the customized `managed = False` from SalesforceModel because it is less and less important (the commit with edited README) and it is not standard in Django. What do you mean?

**Comment by philchristensen** [comment]
That makes sense to me.

**Comment by hynekcer** [comment]
It is complete now.

(The comment expected that the next release will be 0.8 - sometimes in autumn.)

**Comment by hynekcer** [comment]
I'm creating a fixed copy of this PR. The only bug is that it closes the issue 190, not 160. The number 160 was also in the name of the test directory, that made a big diff.

**Pull request closed without merging**
