### PR TITLE
Version v3.2 for Django 3.2

### PR DESCRIPTION
**Pull request by hynekcer**
* Add support for Django 3.2
* Remove the old code for Django 1.11

The tests use Django 3.2 rc1 currently.
Please run tests also on Travis.
Our new release will be useful before final Django 3.2 (April 2021).

### CODE REVIEW

**Comment by hynekcer** [comment]
Release django-salesforce v3.2
------------------------------------------
**Fix `inspectdb` for Django 3.2**

I found a bug in `inspectdb` with Django 3.2. The fix is in three lines of new code.
Also the test infrastructure is a bit improved.

It is pushed directly to main branch with a tag [v3.2](https://github.com/django-salesforce/django-salesforce/commit/c28765cd58bcb556e8d295d85272caf502903183). I think that everything is ready here on Github for the new release. @philchristensen, please upload it to PyPI and optionally check it and create *.whl.

Django 3.2 would be released today on April 6th 2021 (It is an information from their [3.2 roadmap](https://code.djangoproject.com/wiki/Version3.2Roadmap) and their issue tracker has also no bugs targeted to version 3.2. So it seems real.)

**Comment by philchristensen** [comment]
Got it, I’ll do the release shortly!

**Comment by philchristensen** [comment]
Sorry for the delays, as usual, but I just pushed the release now.

https://pypi.org/project/django-salesforce/3.2/

**Comment by philchristensen** [comment]
Having a hard time getting the release notes to appear after publishing your draft. Not sure if it's a caching issue or what but I'm on it.

**Comment by hynekcer** [comment]
Hello Phil !

Thank you very much for the new release.

Maybe the problem with the lost release comment could be caused by me 
last Tuesday. I added the tag v3.2 too soon and directly by "git tag 
..." and "git push ...". Should it be by github web?

Should it be created again completely new?

Hynek

**Comment by philchristensen** [comment]
No, it shouldn’t make a difference. If need be I’ll ask GitHub support.

-Phil
sent from my phone

**Comment by philchristensen** [comment]
Ah, yes, I guess it was because the tag wasn't made on `main`. I recreated the tag and copied the text in again and now everything is working correctly.

**Pull request merged**
