### PR TITLE
Version 0.8.1

### PR DESCRIPTION
**Pull request by hynekcer**
I want to release a new version 0.8.1, mainly in order to fix the regression #226, that was reported recently again.
The best day will be on Monday, May 20th, that date is in the changelog.

### CODE REVIEW

**Comment by philchristensen** [comment]
I'm ready to release this today if it's still good to go.

**Comment by hynekcer** [comment]
Yes, I think that the regression #226 in 0.8 reported last week again is a reason for a new version. I waited for time for writing tests, but it is better to not wait more. Probably spelling should be fixed in CHANGELOG or release notes draft please.

**Comment by philchristensen** [comment]
Haven't forgotten about this, just haven't been able to get to it yet...

**Comment by hynekcer** [comment]
Added a fix for #234. It is a safe change. Only the command "query_topology" is moved to the right place after `pre_sql_setup()` where the query mapping is finalized.

**Pull request merged**
